Update the Norcroft makefile
pnggroup/libpng pull request #348
Opened 2020-10-31 20:22 UTC by ccawley2011

2022-09-18 22:10 UTC, ctruta requested changes

2022-09-18 22:10 UTC, ctruta commented on scripts/makefile.acorn
> +	copy @.scripts.pnglibconf/h/prebuilt $@ ~CF~V
From looking at the surrounding commands, shouldn't `copy` be `Copy`, for stylistic reasons?

Another question, out of curiosity: are `~CF~V` flags? And are they necessary? They look very cryptic, and I'd rather not include them, if possible.

2022-09-18 22:10 UTC, ctruta commented on scripts/!MkAcorn,fd7
> +WimpSlot -min 4096K
This file shouldn't be here.

2024-01-15 01:36 UTC, jbowler commented on scripts/makefile.acorn
> +	copy @.scripts.pnglibconf/h/prebuilt $@ ~CF~V
> Another question, out of curiosity: are `~CF~V` flags? And are they necessary? They look very cryptic, and I'd rather not include them, if possible.

https://www.riscosopen.org/wiki/documentation/show/*Copy

so `~CF-V` translates to `-i`, or maybe it's `-if`

It would be more in keeping with the other makefiles to use "~f-v"; "f" is required to overwrite an existing file so $(COPY) pretty much has to be "COPY a b ~F" to work.

The makefile should also be renamed; it's not Acorn (Pace might be more accurate yet still wrong) and it's not the brothers Norcroft, it really is RISCOS!

2024-01-17 19:20 UTC, ctruta commented on scripts/makefile.acorn
> +	copy @.scripts.pnglibconf/h/prebuilt $@ ~CF~V
> > Another question, out of curiosity: are `~CF~V` flags? And are they necessary? They look very cryptic, and I'd rather not include them, if possible.
> 
> https://www.riscosopen.org/wiki/documentation/show/*Copy
> 
> so `~CF-V` translates to `-i`, or maybe it's `-if`
> 
> It would be more in keeping with the other makefiles to use "~f-v"; "f" is required to overwrite an existing file so $(COPY) pretty much has to be "COPY a b ~F" to work.

Ok, thank you. As I understand your explanation, I actually agree that `Copy a b ~F~V` is the way to go.

> The makefile should also be renamed; it's not Acorn (Pace might be more accurate yet still wrong) and it's not the brothers Norcroft, it really is RISCOS!

Yeah, but Acorn is customarily used (in zip/unzip, in zlib, etc.). And then, it's not only the practice of going by the name of the original makers of RISCOS (which is Acorn), but there's also, quite often, Apple (instead of Darwin or Mac), Microsoft (instead of Windows) -- yes yes I know that Acorn is no longer around, but their existence deserves mentioning -- and I don't mean just the 'A' in ARM.....

2024-01-17 19:36 UTC, ccawley2011 commented on scripts/makefile.acorn
> +	copy @.scripts.pnglibconf/h/prebuilt $@ ~CF~V
"~C" is needed because otherwise it requires user input before copying takes place. In addition, the ~ disables the option following it, so "~F~V" would disable force rather than enabling it.

2024-01-17 19:57 UTC, jbowler commented on scripts/makefile.acorn
> +	copy @.scripts.pnglibconf/h/prebuilt $@ ~CF~V
Ah.  I find it very difficult to tell the difference between "~" and "-" on the computer screen, and I haven't worked on RISCOS since the end of the '80s :-)  So the form as specified originally is correct but confusing to me at least.  It could be written F~C~V (IRC).

RISCOS can't be blamed for the syntax; I think it comes from the BASIC implementation written around 1975 (hence the need to prompt to swap floppy disks).  The need to negate options comes from Copy$Options which might have been specified with CV (for example), I can't remember if that can be overridden globally within the makefile, probably not.

2024-02-03 15:26 UTC, ctruta commented
I applied my own changes directly onto the original commit, based on the discussion with @ccawley2011 and @jbowler.
See ab6d97b7c8be42021a9f33c42934ddde1c90b253.

2024-02-03 15:26 UTC, closed without merging