add CMake config file that follows CMake conventions
pnggroup/libpng pull request #545
Opened 2024-02-15 15:52 UTC by bebuch

New functionality:

- add a CMake config file to the install, so an installed libpng can be found via `find_package(libpng)`
- mark API header includes as SYSTEM headers in install, so warnings in these headers can be disabled

Changed behavior:

- export the target `libpng` as `libpng::libpng` which follows the CMake convention for exported targets (previous it was just `libpng`)
- install CMake files to `lib/cmake/libpng` instead of `lib/libpng` to follow the CMake convention

2024-02-15 17:33 UTC, ctruta requested changes
The code looks good overall -- but see my comment about the `libpng` vs. `PNG` namespace.

I would also like to have one commit per one task, submitted on top of the tree, as a general rule. We are sticking to a linear history, going forward, and we reserve the branches for the time when we fork new libpng versions. Could you please squash all commits, then rebase?

Last, if you could please update `scripts/cmake/AUTHORS.md` 🙂

2024-02-15 17:33 UTC, ctruta commented on CMakeLists.txt
> +          NAMESPACE "libpng::"
I would prefer the namespace `PNG::` instead of `libpng::`, consistently with the rest of the libpng API. (Cf. the names `png_*` for functions, and `PNG_*` for macros, and `png.h` for the header file, etc.)

Moreover, considering that the CMake module name is `FindPNG`, and similar to `FindZLIB`, I would, again, prefer the name `PNG::` in uppercase, instead of the name `png::` in lowercase.

2024-02-15 19:00 UTC, bebuch commented on CMakeLists.txt
> +          NAMESPACE "libpng::"
Thanks for the fast reply, I will look into it tomorrow.

It would be great to have consistency with the PNG module. Currently I need an additional wrapper to get this.

To get full consistency by default I would need to do 3 changes:

1. Namespace PNG::
2. Target name export as PNG (so we get PNG::PNG from find_package; the target name during build can remain libpng)
3. Change the install directory to {CMAKE_INSTALL_LIBDIR}/cmake/png

If this looks good to you, I will do it tomorrow. (Alongside with the Authors addition and the squash.)

2024-02-16 08:59 UTC, ctruta commented on CMakeLists.txt
> +          NAMESPACE "libpng::"
@bebuch any confusion is on us. There are historical reasons, which may as well be called historical excuses, and they date back to the earliest days when the format name was PNG and the library name was _pnglib_ (akin to _zlib_). It was renamed from _pnglib_ to _libpng_ before the release of version 1.0 back in 1995, but everything else named `png_foo` inside remained as-is until this very day. I mean, the short name was changed; but the long name (i.e. _The PNG Reference Library_) remained in place.

The `PNG` and `png` namespaces are to be used as follows:
 * C programming: `png_foo` for functions and friends, `PNG_BAR` for macros.
 * C source file names: `pngfoo.c` and `pngbar.h`.
 * CMake names: `PNG_FOO` -- except for the `PNGLIB` version names at the top of the main CMake lists file.
 * Pretty much anything else other than directory names, archive names and pkgconfig file names (or so I think).

The `libpng` namespace is to be used as follows:
 * Directory names: `libpng/`, `include/libpng16/`
 * Library file names: `libpng.a`, `libpng16.a`, `libpng16.so`, and friends.
 * Pkgconfig file names: `libpng.pc`, `libpng16.pc`, `libpng-config`, `libpng16-config`
 * Archive file names: `libpng-1.6.42.zip`, containing `libpng-1.6.42/*`

I hope these rules will at least in part justify path names like `/usr/include/libpng16/pnglibconf.h` 🤨

2024-02-21 18:43 UTC, bebuch commented on CMakeLists.txt
> +          NAMESPACE "libpng::"
Sorry for the delay and thank you for your fast and detailed explanation! :-)

I created a new PR #550 with only the System Header part.

I will update this PR in the next days. My aim is to provide a CMake Config file which can be used with [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html). My secondary goal is to become directly backwards compatible with [`FindPNG`](https://cmake.org/cmake/help/latest/module/FindPNG.html).

Currently other projects include libpng via CMake's `FindPNG` module:

```cmake
find_package(PNG)
```

I configure my 3rdparty libraries with `CMAKE_FIND_PACKAGE_PREFER_CONFIG=ON`, so they prefer CMake Config Files over CMake Modules. I provide a CMake Config File myself, which mimics the FindPNG Module by creating a Target `PNG::PNG`.

`install_root/lib/cmake/png/PNGConfig.cmake`:

```cmake
if(NOT TARGET PNG::PNG)
    include(CMakeFindDependencyMacro)
    find_dependency(libpng)
    add_library(PNG::PNG INTERFACE IMPORTED)
    target_link_libraries(PNG::PNG INTERFACE libpng::png_shared)
endif()
```

The `find_dependency(libpng)` resolves to the CMake Config File of libpng, that my current PR here provides.

If I understand you correctly, you want the CMake namespace for all targets to always be `PNG::`.

- `PNG::png_shared`
- `PNG::png_static`
- ...

In this case, however, the name of the config file and the directory in which it is installed should also be changed to `PNG`. Otherwise, `find_package(libpng)` would create targets in the namespace `PNG::`. If the file and directory name are also adjusted, `find_package(PNG)` would be used and the targets in the namespace `PNG::` would be obtained as expected.

I think that makes perfect sense. In this case, I would simply create the target `PNG::PNG` and have it forwarded to `PNG::libpng_shared` as shown before. This would give us the same functionality in the config file as in the old `FindPNG` module.

All projects that currently use `find_package(PNG)` would continue to function unchanged, but could simply use the new PNG config file via `CMAKE_FIND_PACKAGE_PREFER_CONFIG=ON` and thus benefit from its advantages.

New projects could explicitly request the config file with `find_package(PNG CONFIG)` and thus build directly against `PNG::libpng_shared` or `PNG::libpng_static` at any time.

2024-02-21 22:09 UTC, ctruta commented on CMakeLists.txt
> +          NAMESPACE "libpng::"
Thank you. Smaller pull requests that are easier to review and test are always extra-appreciated.

I want to let you know a very badly kept secret: a new libpng version is coming up, tentatively called "libpng-ng". If you want to clean up things and change conventions in the sense of making them healthier, even if that means breaking compatibility, then go for it -- now's the time! (Seriously!!)

I will not apply such changes to the 1.6.x line, but that should be ok for those libpng users who don't want anything changed (because IIABDFI). Many libpng users haven't updated libpng in years, which is fine for them and fine for us, too; even if we do fix bugs in the meantime, they seem to not care unless our new fixes happen to solve their old defects.

On the other hand, if you can bring more small changes for the 1.6.x line, in the sense of them being non-disruptive net benefits, like the one in #550, then, sure, please bring!

> Sorry for the delay and thank you for your fast and detailed explanation! :-)

Please do not worry about delaying. I am, too, sometimes fast but other times very very slow to respond, depending on what I happen to be focusing at any given moment.

2024-02-23 22:22 UTC, sergiud commented on CMakeLists.txt
> +                             SYSTEM PUBLIC
As a minor remark, the `SYSTEM` modifier is not only redundant but in fact unnecessarily restrictive as include directories of imported targets are brought as system include directories anyway unless [`NO_SYSTEM_FROM_IMPORTED`](https://cmake.org/cmake/help/latest/prop_tgt/NO_SYSTEM_FROM_IMPORTED.html) is set. See also the CMake reference documentation for the [`SYSTEM`](https://cmake.org/cmake/help/latest/prop_tgt/SYSTEM.html#prop_tgt:SYSTEM) property.

2024-02-24 14:18 UTC, ctruta commented on CMakeLists.txt
> +                             SYSTEM PUBLIC
Thank you for your observation, @sergiud.

One thing that baffles me about the SYSTEM modifier is that it is said to be introduced in CMake 3.25. And yet, the verification of commit 7b888092b9f5d249e7baa7bd43ee14f560cd0ae1 with older versions of CMake was successful. Moreover, I just had a test run on a very old Linux install in a Docker container, running CMake 3.7. That old CMake was happy to take the SYSTEM modifier without even breaking a sweat.

I like it when things work, but not so much when they work without me understanding why...

2024-03-01 12:38 UTC, bebuch commented on CMakeLists.txt
> +                             SYSTEM PUBLIC
@sergiud Thanks for pointing out, I didn't know that!

2024-03-01 12:45 UTC, bebuch commented on CMakeLists.txt
> +          NAMESPACE "libpng::"
That sounds great! A more modern version would be great, even if it takes a long time for it to catch on. On the other hand, [zlib-ng](https://github.com/zlib-ng/zlib-ng) has demonstrated that it's really worth it!

As far as user updates are concerned, we also supply software to other companies. Some of these companies now run security testers on every piece of software and they complain accordingly if outdated 3rd party libs are used. It could well be that such tools will change things in the near future ;-)

2024-03-01 12:48 UTC, bebuch commented
I have now changed the PR so that it creates the config files I wanted and does not touch anything else. Ready to merge from my side! 😸

2024-07-22 13:19 UTC, bebuch commented
@ctruta If you find some time to work on libpng, it would be nice if you could merge this. That way we can use 1.6.44 without a patch once that is tagged. 🙂

2024-09-07 10:42 UTC, bebuch commented
@ctruta Since I just saw that you are active again, it would be nice if you could merge this ;-)

2024-09-08 16:50 UTC, ctruta commented
> @ctruta Since I just saw that you are active again, it would be nice if you could merge this ;-)

My apologies for taking so long, and my appreciations for your patience. This PR is next in line.

2024-09-08 19:18 UTC, ctruta commented
@bebuch Integrated in master, and many thanks. This is super-useful.

Please don't mind me for modifying your commit directly, instead of asking you to do it in a review. After so much wait, now a lot of people want me to push a new release, sooner instead of later. I hope that you accept my modification -- BUT if you do have objections, feel free to submit another PR.

2024-09-08 19:18 UTC, closed without merging